### ISSUE TITLE
Crash with modpack with starminer

### ISSUE THREAD

**Issue by reuben-matus** [CrucibleMC/Crucible#125]
Startup fails stating "A problem occurred running the Server launcher" when using star miner mod due to class not found errors
here is the attached log if there any way around it (maybe in config or an update)

[fml-server-3.log](https://github.com/CrucibleMC/Crucible/files/10810418/fml-server-3.log)

**Comment by juanmuscaria** [comment]
Please remove foamfix, it's not needed and seems to be the one causing the issue

**Comment by reuben-matus** [comment]
Removed foam fix still got a very similar error :/
[fml-server-latest.log](https://github.com/CrucibleMC/Crucible/files/10821120/fml-server-latest.log)

**Comment by juanmuscaria** [comment]
I fear the mod may not be compatible

**Comment by reuben-matus** [comment]
aw okay :(

**Comment by MasqueOu** [comment]
I haven't tested it on my side, wouldn't the concern come from the fact that the Desktop is hosted on OneDrive by chance?

**Comment by EverNife** [comment]
Well, from the logs the server crash right after 
```[Starminer]Injected additional code to Entity.onEntityUpdate```

If tested and it only happens when starminer is present, than probably is a mod compat issue.

Usually these instrusive mods are not well compatible with hybrids.

It seems the source code is not open as well, making it even harder to know if its a problem that can be fixed on our end.
