### ISSUE TITLE
Multi Threading

### ISSUE THREAD

**Issue by MaxifeuxG** [CrucibleMC/Crucible#30]
Hello I would like to know if there is the Multi Threading on crucible

**Comment by evernife** [comment]
Multi Threading is in all Servers, bukkit, sponge, cauldron, thermos, crucible.

Now, if you are asking if we changed the base game to work on multithreads, no, we don't intent to do that.

That would need a entire rewrite of the game logic, and probably, most mods would not even work.

**Comment by evernife** [comment]
https://github.com/CrucibleMC/Crucible/issues/10

**Comment by MaxifeuxG** [comment]
Good evening I was wondering because of API but in more resente versions did it that's why I wanted to ask you thank you anyway

**Comment by spannerman79** [comment]
@MaxifeuxG your confusing between BukkitAPI, SpongeAPI and the ForgeAPI.

Bukkit (Spigot/Paper/etc) uses multi theading on **newer** versions.  This (Crucible) is not only based on 1.7.10 bukkit but also 1.7.10 Forge too.

As outlined ( [here](https://github.com/CrucibleMC/Crucible/issues/10#issuecomment-595036400) ) before it was attempted but due to the way forge is coded in 1.7.10 moving from sync to assync broke ~90% of mods including but not limited to Team CoFH mods, Tinkers, Mekanism and every single biome generation mod.

Can it be done? Sure.  Will you be able to use mods? ~90% chance it will be a no.  If you want assync then modify SpigotMC and use plugins and not mods.

**Comment by MaxifeuxG** [comment]
hello I ask myself the question because in the higher version forge + spigot and bukkit I can not say that it is completely stable but there is a development on it to make it stable I wanted to know if for crucible there will be a crucibleasync later

**Comment by evernife** [comment]
Can you show us that API? for me to understand exactly what you are asking for?

From what I see, we are talking about different things :/

**Comment by MaxifeuxG** [comment]
I'm talking about multi thread and yes it and open source but in 1.12.2 and it's cumserver

**Comment by spannerman79** [comment]
@evernife close this as a duplicate of https://github.com/CrucibleMC/Crucible/issues/10

OP obviously doesn't understand what they are asking for even after being explained the differences between the different API's and MC versions on each API.

**Comment by MaxifeuxG** [comment]
ok
