### ISSUE TITLE
Crash with RecurrentComplex

### ISSUE THREAD

**Issue by GedeonGrays** [CrucibleMC/Crucible#41]
_Hello o/_

**Crucible Version:** 4.1 (version with fix a written book by juanmuscaria in Discord)
**RecurrentComplex Version:** 0.9.7.1.1
**Crash report:** https://pastebin.com/vtVsawXA

Crash during server startup.

**Comment by juanmuscaria** [comment]
Looks like the mod is using the internals of joptsimple (the library used to parse command line options and arguments) https://github.com/Ivorforce/RecurrentComplex/blob/d8d1246583da009eb86af34462b1de203bc448a1/src/main/java/ivorius/reccomplex/structures/generic/matchers/BiomeMatcher.java#L47
I can try to make a patch later to add this missing method that was removed probably because of library version differences.

**Comment by GedeonGrays** [comment]
The last commit didn't fix the problem. The server still stops at startup.
Crash report: https://pastebin.com/L5cTXK7x

**Comment by evernife** [comment]
RecurrentComplex  seems to use 4.5

![image](https://user-images.githubusercontent.com/11357801/107442535-0018a600-6b16-11eb-9051-97429bc56901.png)

**Comment by Irgendwer01** [comment]
@evernife Next issue is that when downgrading Jaopt-simple Crucible just will crash (https://discordapp.com/channels/682358465175355393/682366014939201544/805576978216255569)

**Comment by evernife** [comment]
I tried to make a fix on the mod itself https://github.com/FinalCraftMC/RecurrentComplex/commit/28ebb85f18bd32d984f8c25dc71603c7b977ff8c. 

Can you try this version of the mod ?
https://github.com/FinalCraftMC/RecurrentComplex/releases

**Comment by evernife** [comment]
Seems to be working on my tests.

![image](https://user-images.githubusercontent.com/11357801/107444351-3572c300-6b19-11eb-98de-d08a683a9fef.png)
